Public Module Sfx
    Public ReadOnly PlayerHit As String = NameOf(PlayerHit)
    Public ReadOnly Take As String = NameOf(Take)
    Public ReadOnly Eat As String = NameOf(Eat)
    Public ReadOnly WooHoo As String = NameOf(WooHoo)
    Public ReadOnly Shucks As String = NameOf(Shucks)
    Public ReadOnly Craft As String = NameOf(Craft)
    Public ReadOnly Yoink As String = NameOf(Yoink)
    Public ReadOnly Tasty As String = NameOf(Tasty)
    Public ReadOnly EnemyDeath As String = NameOf(EnemyDeath)
    Public ReadOnly EnemyHit As String = NameOf(EnemyHit)
    Public ReadOnly EnemyMiss As String = NameOf(EnemyMiss)
    Public ReadOnly PlayerDeath As String = NameOf(PlayerDeath)
    Public ReadOnly PlayerMiss As String = NameOf(PlayerMiss)
End Module
